/*CRIA O GENERATOR PARA CAMPO ID_USUARIO*/
CREATE GENERATOR GEN_ID_USUARIO;

/*CRIA TRIGGER PARA USUARIO*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_USUARIO FOR USUARIO ACTIVE
BEFORE INSERT position 0 
AS 
BEGIN 
    NEW.ID_USUARIO=GEN_ID(GEN_ID_USUARIO,1);
END^

SET TERM ; ^
---------------------------------------------------------

SELECT * FROM CLIENTE

/*CRIA O GENERATOR PARA CAMPO ID_CLIENTE*/
CREATE GENERATOR GEN_ID_CLIENTE;

/*CRIA TRIGGER PARA CLIENTE*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_CLIENTE FOR CLIENTE ACTIVE
BEFORE INSERT position 0 
AS 
BEGIN 
    NEW.ID_CLIENTE=GEN_ID(GEN_ID_CLIENTE,1);
END^

SET TERM ; ^
---------------------------------------------------------------

/*CRIA O GENERATOR PARA CAMPO ID_EMPRESA*/
CREATE GENERATOR GEN_ID_EMPRESA;

/*CRIA TRIGGER PARA EMPRESA*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_EMPRESA FOR EMPRESA ACTIVE
BEFORE INSERT position 0 
AS 
BEGIN 
    NEW.ID_EMPRESA=GEN_ID(GEN_ID_EMPRESA,1);
END^

SET TERM ; ^
-----------------------------------------------------
CREATE GENERATOR GEN_ID_FORNECEDOR;

/*CRIA TRIGGER PARA FORNECEDOR*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_FORNECEDOR FOR FORNECEDOR ACTIVE
BEFORE INSERT position 0 
AS 
BEGIN 
    NEW.ID_FORNECEDOR=GEN_ID(GEN_ID_FORNECEDOR,1);
END^

SET TERM ; ^
------------------------------------------------------------
CREATE GENERATOR GEN_ID_PRODUTO;

/*CRIA TRIGGER PARA PRODUTO*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_PRODUTO FOR PRODUTO ACTIVE
BEFORE INSERT position 0 
AS 
BEGIN 
    NEW.ID_PRODUTO=GEN_ID(GEN_ID_PRODUTO,1);
END^

SET TERM ; ^
--------------------------------------------------------------
CREATE GENERATOR GEN_ID_FORMA_PGTO;

/*CRIA TRIGGER PARA FORMA_PGTO*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_FORMA_PGTO FOR FORMA_PGTO ACTIVE
BEFORE INSERT position 0 
AS 
BEGIN 
    NEW.ID_FORMA_PGTO=GEN_ID(GEN_ID_FORMA_PGTO,1);
END^

SET TERM ; ^
------------------------------------------------------------------
CREATE GENERATOR GEN_ID_COMPRA;

/*CRIA TRIGGER PARA COMPRA*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_COMPRA FOR COMPRA ACTIVE
BEFORE INSERT position 0 
AS 
BEGIN 
    NEW.ID_COMPRA=GEN_ID(GEN_ID_COMPRA,1);
END^

SET TERM ; ^
-------------------------------------------------------------
CREATE GENERATOR GEN_ID_VENDA;

/*CRIA TRIGGER PARA VENDA*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_VENDA FOR VENDA ACTIVE
BEFORE INSERT position 0 
AS 
BEGIN 
    NEW.ID_VENDA=GEN_ID(GEN_ID_VENDA,1);
END^

SET TERM ; ^